pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                script {
                    // Sanitize project name and version by removing non-printable characters
                    def NAME = sh(script: 'mvn -q -DforceStdout help:evaluate -Dexpression=project.name | tr -d \'[:cntrl:]\' | awk \'{print $1}\'', returnStdout: true).trim()
                    def VERSION = sh(script: 'mvn -q -DforceStdout help:evaluate -Dexpression=project.version | tr -d \'[:cntrl:]\' | awk \'{print $1}\'', returnStdout: true).trim()
                    
                    // Print out NAME and VERSION for debugging
                    echo "Project Name: ${NAME}"
                    echo "Project Version: ${VERSION}"
                    
                    // Run the jar file with sanitized name and version
                    sh "java -jar target/${NAME}-${VERSION}.jar"
                }
            }
        }
    }
}
